import Link from "next/link";
import { notFound } from "next/navigation";
import { getSession } from "@/lib/storage";
import { diffSnapshots } from "@/lib/diff";
import { StatGrid } from "@/components/views/StatGrid";
import { SinceLastVisit } from "@/components/views/SinceLastVisit";
import { SessionToolbar } from "@/components/SessionToolbar";
import { SessionTabs } from "@/components/SessionTabs";

export const dynamic = "force-dynamic";

export default async function SessionPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const session = await getSession(id);
  if (!session) notFound();

  const current = session.snapshots[session.snapshots.length - 1];
  const previous =
    session.snapshots.length > 1
      ? session.snapshots[session.snapshots.length - 2]
      : null;
  const diff = previous ? diffSnapshots(previous, current) : null;

  const fetchedAt = new Date(current.fetchedAt).toLocaleString();

  return (
    <main className="flex flex-col gap-6 px-6 py-8 max-w-7xl w-full mx-auto">
      {/* Top bar */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <Link
          href="/"
          className="text-sm text-zinc-500 hover:text-zinc-900 dark:hover:text-zinc-100 transition"
        >
          ← All sessions
        </Link>
        <span className="text-xs text-zinc-500">
          Fetched {fetchedAt} · {session.snapshots.length} snapshot
          {session.snapshots.length === 1 ? "" : "s"}
        </span>
      </div>

      <SessionToolbar
        sessionId={session.id}
        sessionName={session.name}
        repoUrl={session.repoUrl}
        targetId="screenshot-target"
      />

      {/* Everything inside #screenshot-target is captured when screenshotting */}
      <div id="screenshot-target" className="flex flex-col gap-6">
        {diff && <SinceLastVisit diff={diff} />}

        {current.repo.description && (
          <p className="text-zinc-600 dark:text-zinc-400 max-w-3xl">
            {current.repo.description}
          </p>
        )}

        {current.repo.topics.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            {current.repo.topics.map((t) => (
              <span
                key={t}
                className="text-xs px-2 py-0.5 rounded-full bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400"
              >
                {t}
              </span>
            ))}
          </div>
        )}

        <StatGrid snap={current} />

        <SessionTabs snap={current} />

        <footer className="text-xs text-zinc-500 text-center pt-4 border-t border-zinc-200 dark:border-zinc-800">
          Generated by GitVision ·{" "}
          <span className="font-mono">{current.repo.fullName}</span>
          {current.rateLimitInfo && (
            <>
              {" "}
              · Rate limit: {current.rateLimitInfo.remaining}/
              {current.rateLimitInfo.limit}
            </>
          )}
        </footer>
      </div>
    </main>
  );
}
